### ISSUE TITLE
multi-line strings show as uncovered

### ISSUE THREAD

**Issue by joel-arthur** [rduldulao/py-coverage-view#6]
A function like the following:

def foo():
   """
   Returns...
   param:....
   """
   return true

Will show that the comment at the top is uncovered.

**Comment by rduldulao** [comment]
Hi @joel-arthur.  Thanks for the report.  Will try to get this fixed in next release.  Sorry for the late response.

**Comment by rduldulao** [comment]
Hi @joel-arthur  -- Please there is a new version published.
